# Railway.app deployment configuration with nixpacks
[variables]
NODE_VERSION = "18"
NPM_CONFIG_PRODUCTION = "true"

[phases.build]
dependsOn = ["install"]
cmds = ["echo 'Build completed - Talk pAI ready for Railway'"]

[phases.install]
cmds = ["npm ci --only=production"]

[start]
cmd = "node server.js"

[staticAssets]
"public" = "/"

# Health check configuration for Railway
[healthcheck]
path = "/health"